# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: Npm@1
  displayName: 'Install npm packages'
  inputs:
    workingDir: '$(System.DefaultWorkingDirectory)'
    verbose: false
- task: Npm@1
  displayName: 'npm run test'
  inputs:
    command: custom
    workingDir: '$(System.DefaultWorkingDirectory)'
    verbose: false
    customCommand: 'run test'
- task: Npm@1
  displayName: 'Build project'
  inputs:
    command: custom
    workingDir: '$(System.DefaultWorkingDirectory)'
    verbose: false
    customCommand: 'run build'
